language: haskell
ghc: 7.8
script:
  - cabal configure --enable-tests --enable-library-coverage -v2 && cabal build && cabal test
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=tests tests
notifications:
  email: true
before_deploy: "./bundle/build.sh"
deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file:
    - bundle/*.tar.gz
    - bundle/*.sha
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
