language: haskell
ghc: 7.8
script:
  - cabal configure --enable-tests --enable-library-coverage -v2 && cabal build && cabal test
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=tests tests
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: s/P21lZPgcrXosn6DXmJXbcgCXR6NXT7p1dYXn6Uw9+M/xhKao0FC32+Q8oKDJohobhl1hj/Tn9eY0z00slfs5o5y83oSoQna3SJ9n85TRQCDpI6fMdoioH8Enos7MLAqt1cDAPYzH
  file:
    - dist/build/docgen/docgen
    - dist/build/hierarchy/hierarchy
    - dist/build/psc-make/psc-make
    - dist/build/psc/psc
    - dist/build/psci/psci
    - prelude/prelude.purs
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
